name: Update Site

on:
  push:
    branches: master
    paths-ignore: '.github/**'
  
jobs:
  updatesite:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install hugo and generate static html
        run: |
          brew install hugo
          hugo -D
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          repo: corestack-awsworkshop/corestack-awsworkshop.github.io
          dir: public
          branch: main
          token: ${{ secrets.GITKEN }}
